# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e8dfe854366b5a0d4ff683462d5eb9d652ff1be7b51e8b4edb8c502d825e34f500de949e7cf7c466ee55c549daf3d4f10822999bc87d3a11035cad86b8c2f75

test:
  secret_key_base: 52f06ea0c69c3b56f8f4b55ccb6a6c3f20be9bc319cfd63901885f008d9b805faf0282534fcb02c030b23eda60f93b3cca7e84475ffad406a67a7f86273c9791

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  google_analytics_code: YOUR CODE HERE
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>